name: compile-packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - name: Add packages
        run: |
          julia -e 'using Pkg; Pkg.add(["QuadGK"])'
      - name: move the julia directory
        run: |
          mv ~/.julia /home/runner/work/julia-colab/julia-colab/.julia
      - name: commit to different branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: compiled-packages
      
      
